# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rrrrraquel's design portfolio
email: eu@rrrrraquel.com
description: > # this means to ignore newlines until "baseurl:"
  Estudante de Design da Universidade de Brasília desde 1/2012. Trabalha com áreas diversas do design, sempre com foco em interação do usuário. É apaixonada por educação inclusiva e busca trabalhos que englobam esta área. Tem interesses ainda nas áreas de Design de Serviços, User Experience, Pedagogia, Psicologia e tecnologia
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rrrrraquel.com" # the base hostname & protocol for your site
twitter_username: imboldlygoing
github_username:  rppacheco

#permalink structure
permalink: /:categories/:title

#my pages

links:
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire-me
    url: /hire-me

# Build settings
markdown: kramdown
